


 ***********************************************9/12/2021 10:10:40 PM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	HarougeAPI.Controllers.HospitalController.ActiveteHospital (HarougeAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	9/12/2021 10:10:40 PM


Source Exception               ====> 	   at Services.Services.HospitalServices.ActiveHospital(String hospitalId, Boolean isActive) in D:\Projects\source\repos\Pathology-Department\Services\Services\HospitalServices.cs:line 28
   at HarougeAPI.Controllers.HospitalController.ActiveteHospital(String id, Boolean isActive) in D:\Projects\source\repos\Pathology-Department\HarougeAPI\Controllers\HospitalController.cs:line 103
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)





 ***********************************************9/12/2021 10:15:04 PM*****************************************************


Status Code                    ====> 	400


Path Error                     ====> 	HarougeAPI.Controllers.HospitalController.ActiveteHospital (HarougeAPI)


Type Execut Exception          ====> 	ExecuteException


Exception Masseges             ====> 	Object reference not set to an instance of an object.


inner Exception                ====> 	No Inner Exception


Date Exception                 ====> 	9/12/2021 10:15:04 PM


Source Exception               ====> 	   at Services.Services.HospitalServices.ActiveHospital(String hospitalId, Boolean isActive) in D:\Projects\source\repos\Pathology-Department\Services\Services\HospitalServices.cs:line 28
   at HarougeAPI.Controllers.HospitalController.ActiveteHospital(String id, Boolean isActive) in D:\Projects\source\repos\Pathology-Department\HarougeAPI\Controllers\HospitalController.cs:line 103
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


